# Set env variables
export BROWSER='open'
export TERMINAL='iterm'
export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less'
export BAT_THEME="Solarized (light)"
export MANPAGER='nvim +Man!'

# Set paths
# Stop macOS messing with the PATH variable.
unsetopt GLOBALRCS
if [ -x /usr/libexec/path_helper ]; then
    eval `/usr/libexec/path_helper`
fi

# XDG
# See https://wiki.archlinux.org/title/XDG_Base_Directory
# Also: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
if [[ -z "$XDG_CONFIG_HOME" ]]; then
  export XDG_CONFIG_HOME="$HOME/Library/Preferences"
fi

if [[ -z "$XDG_CACHE_HOME" ]]; then
  export XDG_CACHE_HOME="$HOME/Library/Caches"
fi

if [[ -z "$XDG_DATA_HOME" ]]; then
  export XDG_DATA_HOME="$HOME/Library/Application\ Support"
fi

if [[ -z "$XDG_STATE_HOME" ]]; then
  export XDG_STATE_HOME="$HOME/Library/Application\ Support"
fi

if [[ -z "$XDG_DATA_DIRS" ]]; then
  export XDG_DATA_DIRS="/usr/local/share:/usr/share"
fi

if [[ -z "$XDG_CONFIG_DIRS" ]]; then
  export XDG_CONFIG_DIRS="/Library/Preferences"
else
  export XDG_CONFIG_DIRS="/Library/Preferences:$XDG_CONFIG_DIRS"
fi

if [ ! -w ${XDG_RUNTIME_DIR:="/run/user/$UID"} ]; then
    XDG_RUNTIME_DIR=/tmp
fi
export XDG_RUNTIME_DIR

# Homebrew
export LIBRARY_PATH="/opt/homebrew/lib:$LIBRARY_PATH"

if [ -d /opt/homebrew ] ; then
    BREW_PREFIX=/opt/homebrew
fi

if [ ! -z ${BREW_PREFIX} ]; then
    path=($BREW_PREFIX/bin $path)
    path=($BREW_PREFIX/opt/make/libexec/gnubin $path)
    fpath=($BREW_PREFIX/share/zsh/site-functions $fpath)
fi

# Misc
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"

export ZSH_DISABLE_COMPFIX=true

export PATH="$HOME/.gem/ruby/3.0.0/bin:$PATH"
export PATH="$PATH:/Users/krisms/.local/bin"
export PATH="/usr/local/sbin:$PATH" # not added by default 
